server:
  port: 8089

spring:
  application:
    name: usuario-service

  datasource:
    # Se añade 'createDatabaseIfNotExist=true' para crear la BD automáticamente
    # También se añade 'useSSL=false' y la zona horaria para evitar advertencias en consola
    url: jdbc:mysql://localhost:3306/usuario_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Esto replica las propiedades de formato del primer proyecto
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # Es una buena práctica en microservicios preferir la IP sobre el hostname
  instance:
    prefer-ip-address: true